src/objects/Pivotal_Tracker__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This Stores API Key and Project Id</description>
    <fields>
        <fullName>API_Token__c</fullName>
        <label>API Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PivotalTracker</label>
</CustomObject>

src/classes/PivotalTrackerSetup.cls
public class PivotalTrackerSetup {
    public Pivotal_Tracker__c config {get; set;}
    public Boolean editMode {get; set;}

    public PivotalTrackerSetup() {
        config = Pivotal_Tracker__c.getValues('default');

        if (config == NULL) {
            config = new Pivotal_Tracker__c(Name = 'default');
        }
    }

    public void sync() {
        if (String.isNotBlank(config.API_Token__c)) {
            PivotalTrackerSync.sync();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Synchronization started'));
        }
    }

    public void save() {
        upsert config;
        edit();
    }

    public void edit() {
        editMode = editMode != true;
    }
}