src/objects/Pivotal_Project__c.object
<CustomObject>
    <label>Pivotal Project</label>
    <nameField>
        <label>Pivotal Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pivotal Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pivotal_Story__c.object
<CustomObject>
    <fields>
        <fullName>Pivotal_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pivotal Project</label>
        <referenceTo>Pivotal_Project__c</referenceTo>
        <relationshipLabel>Pivotal Stories</relationshipLabel>
        <relationshipName>Pivotal_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pivotal Story</label>
    <nameField>
        <label>Pivotal Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pivotal Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PivotalTrackerSync.cls
global with sharing class PivotalTrackerSync {
	public List<String> actions = new List<String>{
        'projects',
        'stories'
    };

    private Database.DMLOptions dmo;
    private PivotalTracker tracker;
    private List<Pivotal_Project__c> projects = new List<Pivotal_Project__c>();
    private List<Pivotal_Story__c> stories = new List<Pivotal_Story__c>();
    public List<String> errors = new List<String>();

    global PivotalTrackerSync(PivotalTracker tracker) {
        dmo = new Database.DMLOptions();
        dmo.allowFieldTruncation = true;
        this.tracker = tracker;
    }

    global List<String> start(Database.BatchableContext BC) {
        while (actions.size() < 10) {
            actions.add(actions[actions.size()-1]);
        }
        return actions;
    }

    global void execute(Database.BatchableContext BC, List<String> scope) {


    }

    global void finish(Database.BatchableContext BC) {

    }

    private void sendErrorEmail() {

    }

    private void processScope(List<String> scope) {

    }

    private void processUpsertResults(){
    	
    }
}